### ISSUE TITLE
Good practices

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/AquaResistivity#1]
Wanted to bring some good practices in so they become habits

- Main branch is for master code. So always work in a branch. Each task given should be fully matured in a branch before combining with Main branch
- Great start on function. Like it. Input should be abstracted in to a separate configuration file. You will understand why?
  - See link on why configuration : https://www.codeproject.com/Articles/5319621/Configuration-Files-in-Python
  - We use yaml format: https://stackoverflow.com/questions/38404633/reading-yaml-config-file-in-python-and-using-variables
- TBA

**Comment by vamseeachanta** [comment]
Please invite @saiachanta2728 as collaborator? He will be a team member.

**Comment by samdansk2** [comment]
> Please invite @saiachanta2728 as collaborator? He will be a team member.

Done sir , okay sir .

**Comment by samdansk2** [comment]
Sure sir , 
working on configuration file for the input that should be abstracted into it . 
Yaml format is also one , will do that also 👍

**Comment by samdansk2** [comment]
### Date : 02-02-2024

Hello sir , hope you are doing well. 
I wanted give you insights regarding today's progress :
--> Created a new repo
--> As you said main branch is kept aside for master code. 
--> Created a new branch Named Calci
--> from next time all the calculations and changes can be done in a seperate branch. 
--> Configuration of file is somewhat got a idea
--> Yaml file is  little bit complicated , need to work on it.

**Comment by samdansk2** [comment]
Hello sir , hope you are doing well. 
I am writing this regarding the progress , 

Yaml Python File Format : 
--> Explored the information about yaml file . 
--> Got to know about What is yaml , why we use it 
      and yaml syntax . 
-->  Yaml use key - value pairs 
-->  Explored about Scalars , mappings . 
--> Understood the concepts like list , multi-line 
      scalars . 
--> Yaml indentation is main concern in yaml code.
   -- Tabs are not allowed , spaces and colons are 
      used . 

GitHub : 
--> Wrote the yaml code in Vscode. 
--> Saved the file using .yml extension. 
--> Cloned the repository . 
--> Using git commands , Pushed the yaml file 
     into repository . 
--> Committed the changes. 

Thankyou sir , 
Shaik Samdan.

**Comment by vamseeachanta** [comment]
great job. For all data formats, there are goods and bads. Yaml format has its ups and downs. Yaml and json are almost interchangeable... 

Good job at being consistent so far.

We will have a session sometime next week to bring this program to next level.

**Comment by samdansk2** [comment]
Hello sir , good afternoon 

Created a new python file called seawater resistivity_1 (link below) for calculation in ' Calci ' branch
please see it sir , once go through it , if there are any mistakes let us discuss about that .

https://github.com/samdansk2/Ace-Task-1/blob/Calci/src/seawater_resistivity/seawater_resistivity1.py

Thankyou .

**Comment by vamseeachanta** [comment]
See code updates below:
https://github.com/samdansk2/Ace-Task-1/tree/Calci/src/seawater_resistivity
Key updates:
- I added the conductance data as .csv file (link below)
https://github.com/samdansk2/Ace-Task-1/blob/Calci/src/seawater_resistivity/seawater_conductance_with_temperature.csv
- Also added the csv file location to seawater_resistivity_csv.yml file 
- Step 1: Use this python file (seawater_resistivity_csv_input.py) to do the following (Action SS): 
  - Read from .csv as pandas DataFrame
  - Use the dataframe to get the conductance
  - From conductance, get resistivity = 1/ conductance. 
  - use temperature, salinity value, get the output

**Comment by vamseeachanta** [comment]
At the end of this, this is expected to be a great example to explain how coding is done locally and all the way to a public library. 
Way forward:
- Step 2: Write a test for the above calculation (Action SS): 
- Step 3: Run the test on computer. Also add this test to github actions
- Step 5: Kick this out into another repository named (seawater_conductance). Make this a simple public library and host in pypi.org.

**Comment by vamseeachanta** [comment]
@saiachanta2728 , please follow the code progression and hand-off. A very good example on how to make things happen. 

Keep this pace up @samdansk2

**Comment by samdansk2** [comment]
> See code updates below: https://github.com/samdansk2/Ace-Task-1/tree/Calci/src/seawater_resistivity Key updates:
> 
> * I added the conductance data as .csv file (link below)
>   https://github.com/samdansk2/Ace-Task-1/blob/Calci/src/seawater_resistivity/seawater_conductance_with_temperature.csv
> * Also added the csv file location to seawater_resistivity_csv.yml file
> * Step 1: Use this python file (seawater_resistivity_csv_input.py) to do the following (Action SS):
>   
>   * Read from .csv as pandas DataFrame
>   * Use the dataframe to get the conductance
>   * From conductance, get resistivity = 1/ conductance.
>   * use temperature, salinity value, get the output

Hello sir , want to give you the progress 

As you said ,  Added the .csv file and read data from Dataframe 
analyzed the dataframe rows , columns and values 
calculated the conductance and got the correct resistivity value output .
 
Please see it sir in the Calci branch file called seawater_resistivity_csv1 , after then i will move to write that in Yaml file also ,
Thankyou.

**Comment by vamseeachanta** [comment]
Looks good. Continue coding...

Some things I noticed which I will explain in greater detail in the next session:
- CSV file is more readable. Just use the .csv file path in .yml. Then use pandas to read it and get the .csv and continue.
- The dataframe can just be in code. No need to define it explicitly in code. Just will be there in a variable.
- Notebooks are great for experimenting and first time calculation. Not so good for repeat calculations as it is cumbersome to repeat same thing again and again. Hence script based programming.
- user inputs in code (with keyboard) is good for user-interaction. however, .yml input file is easily maintainable, and we can easily keep these as test cases.

**Comment by samdansk2** [comment]
Hello sir , morning , 

Also wrote the code in yaml file 
Can you please once go through it , if there are any
Mistakes let me know . 

Thank you.

**Comment by saiachanta2728** [comment]
Hello sir , good evening

i have completed the work of removing background using python,but i have
run the code using google colab when u free see the code and say any
changes are there .

Thankyou sir,

**Comment by saiachanta2728** [comment]
Hello sir , good evening

i have completed the work of removing background using python,but i have
run the code using google colab when u free see the code and say any
changes are there .

Thankyou sir,

**Comment by samdansk2** [comment]
hello sir , hope you are doing well .

--> Created the test and able to run the file in terminal 
--> please see it sir  , if there are any flaws
--> otherwise i will further  move with github actions 

thankyou.

**Comment by samdansk2** [comment]
Hello sir, how are you , hope you are doing better. Wanted to give you the progress , 

-> Added the test to GitHub actions 
-> I am unable to figure the errors out 
-> Please see it sir , let us discuss about it. 

Thankyou.

**Comment by vamseeachanta** [comment]
@samdansk2 we will review together and close it.

**Comment by samdansk2** [comment]
reviewed everything ,
