### ISSUE TITLE
pytest Implementation

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/AquaResistivity#3]
@samdansk2 , 

CC: @saiachanta2728 

Great progress on making a start on pytest and github actions.. I am spinning out individual tasks into issues so we can tackle them individually. The key wayforward to successfully run these tests:
a/ Run the same teests locally. Get them to complete successfully
b/ Get these tests run on Github as Actions.

Thank you,

**Comment by samdansk2** [comment]
Guthub actions workflow running successfully , all tests have passed

**Comment by samdansk2** [comment]
![ship](https://github.com/user-attachments/assets/fc99074c-a533-4de4-a4fb-a76502b51db2)
