### ISSUE TITLE
Run Individual projects on virtual Environment

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/AquaResistivity#4]
@samdansk2, Are you running your code on Conda virtual environment?

else get your lessons from @saiachanta2728

**Comment by samdansk2** [comment]
No sir , I am actually using python interpreter

**Comment by samdansk2** [comment]
I am unable to create virtual environment 
There is a error called metadata generation failed 
Because of this also pandas are not being installed in vscode

**Comment by samdansk2** [comment]
> @samdansk2, Are you running your code on Conda virtual environment?
> 
> else get your lessons from @saiachanta2728

Yes sir , already I took notes from @saiachanta2728 regarding virtual environment.

**Comment by samdansk2** [comment]
done with virtual environments , everything is alright
